PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/cb8d2672305c4a2f8740a2c561dd71a16ab3b7a8

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...cb8d2672305c4a2f8740a2c561dd71a16ab3b7a8

cb8d267230 (HEAD, origin/master) xtensa/esp32: Announce the power management state change to feed watchdog
2991418b2e xtensa/esp32: keep cpu clock while configured cpu clock is consistent with the default
39322e1158 xtensa/esp32: Get CPU frequency from the rtc register
1847a67e05 xtensa/esp32: Add sleep reject reasons
5c5e0494f3 xtensa/esp32: Keep VDDSDIO power on if PSRAM is enabled
ffcedfd971 Remove copyright from headers
558dfa28fb nxstyle fix
6a43daa67e Update licenses to Apache 2.0
78797dc1da binfmt/libnxflat/libnxflat_bind.c: Fix syslog formats
ca2cc5133d binfmt/libnxflat/libnxflat_load.c: Fix syslog formats

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/72d9b34fb13958b5798a180f815257446f57f597

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...72d9b34fb13958b5798a180f815257446f57f597

72d9b34f (HEAD -> master, origin/master) netutils/tftpc/tftpc_put.c: Fix syslog formats
5a4bf6b3 netutils/tftpc/tftpc_get.c: Fix a syslog format
eeded9da netutils/ntpclient/ntpclient.c: Fix syslog formats
13424fc4 netutils/ftpc/ftpc_putfile.c: Fix syslog formats
2a3f2ea8 netutils/ftpc/ftpc_putfile.c: Appease nxstyle
7b3ccfa9 netutils/ftpc/ftpc_getfile.c: Fix a syslog format
f83caca9 netutils/ftpc/ftpc_getfile.c: Appease nxstyle
24b6f919 examples/mld: Fix undefined reference to `mld_catfile'
a4ae1592 examples/i2schar: Fix the compile error
736a21f0 examples/chrono: Rename button_daemon to chrono_daemon